name: Release
on:
  push:
    branches: ["master", "main"]
    tags: ["*"]
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v5
        with:
          java-version: 8
          distribution: adopt
          cache: sbt
      - run: sbt -Dsbt.io.jdktimestamps=true ci-release
        if: ${{ github.repository_owner == 'sbt' }}
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
